package com.example.iot.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

/**
 * Entity class representing energy consumption data from IoT devices.
 * This class maps to the 'energy_data' table in the database and stores
 * individual energy readings with their associated timestamps.
 *
 * <p>Key features:
 * <ul>
 *   <li>Unique identification for each reading</li>
 *   <li>Association with source device</li>
 *   <li>Energy consumption measurement</li>
 *   <li>Precise timestamp tracking</li>
 * </ul></p>
 *
 * <p>The entity maintains a many-to-one relationship with Device entity,
 * allowing multiple readings to be associated with a single device.</p>
 *
 * @author Min-Han Li
 * @version 1.0
 * @see com.example.iot.model.Device
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "energy_data")
public class EnergyData {
  /**
   * Unique identifier for the energy reading.
   * Auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * Reference to the device that generated this reading.
   * Establishes a many-to-one relationship with the Device entity.
   */
  @ManyToOne
  @JoinColumn(name = "device_id", nullable = false)
  private Device device;

  /**
   * The actual energy consumption value recorded.
   * Stored as a double precision number.
   */
  @Column(name = "energy_consumed", nullable = false)
  private Double energyConsumed;

  /**
   * The exact time when this reading was recorded.
   * Used for time-series analysis and reporting.
   */
  @Column(nullable = false)
  private LocalDateTime timestamp;
}
